In [1]:
import numpy as np

## Question 1 — Broadcasting and Indexing

You are given:
```python
import numpy as np
arr = np.array([[2, 4, 6],
 [8, 10, 12],
 [14, 16, 18]])
 ```
1. Use slicing to extract the second and third columns.
2. Add a NumPy array [1, 2, 3] to each row using broadcasting.
3. Explain how broadcasting works in this context

In [2]:
arr = np.array([[2, 4, 6],
 [8, 10, 12],
 [14, 16, 18]])

In [3]:
# 1. Use slicing to extract the second and third columns.
second_col = arr[:, 1]
third_col = arr[:, 2]

second_col, third_col

(array([ 4, 10, 16]), array([ 6, 12, 18]))

In [4]:
# 2. Add a NumPy array [1, 2, 3] to each row using broadcasting.
arr2 = np.array([1, 2, 3])
arr_total = arr + arr2

arr_total

array([[ 3,  6,  9],
       [ 9, 12, 15],
       [15, 18, 21]])

3. Explain how broadcasting works in this context

- arr has shape (3, 3)
- arr2 has shape (3,)

> NumPy automatically expands the 1D array [1, 2, 3] to match the shape of the 2D array (3, 3) along the rows. Each row of arr is added elementwise to [1, 2, 3]. This is called broadcasting, which allows vectorized operations between arrays of different but compatible shapes.

```
arr = [[2, 4, 6],
       [8, 10, 12],
       [14, 16, 18]]

arr2 = [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]

arr_total = [[ 2+1,  4+2,  6+3],
             [ 8+1, 10+2, 12+3],
             [14+1, 16+2, 18+3]]

arr_total = [[ 3,  6,  9],
             [ 9, 12, 15],
             [15, 18, 21]]

## Question 2 — Random and Statistical Functions

Create a 4×4 array of random integers between 10 and 50 (inclusive).

Then:
1. Find the mean, standard deviation, and maximum of the array.
2. Replace all elements greater than the mean with 0.
3. Print the modified array.
(Hint: use np.random.randint, np.mean, and boolean indexing)

In [5]:
# Create a 4×4 array of random integers between 10 and 50 (inclusive)
arr = np.random.randint(low=10, high=51, size=(4, 4))
arr

array([[18, 43, 35, 23],
       [44, 32, 48, 15],
       [33, 26, 14, 28],
       [43, 32, 13, 43]])

In [6]:
# 1. Find the mean, standard deviation, and maximum of the array.

arr_mean = np.mean(arr)
print("Array mean :", arr_mean)

arr_std = np.std(arr)
print("Array standard deviation :", arr_std)

arr_max = np.max(arr)
print("Array max value :", arr_max)

Array mean : 30.625
Array standard deviation : 11.307491985405075
Array max value : 48


In [7]:
# 2. Replace all elements greater than the mean with 0.
arr_bool = arr > arr_mean
arr[arr_bool] = 0

In [8]:
# 3. Print the modified array.
print(arr)

[[18  0  0 23]
 [ 0  0  0 15]
 [ 0 26 14 28]
 [ 0  0 13  0]]


## Question 3 — Matrix Operations

Given the matrix:
```python
A = np.array([[4, 2],
              [3, 5]])
```

1. Compute the transpose and inverse of A.
2. Verify that the product of A and its inverse gives an identity matrix (within rounding error).
3. Explain why np.dot() is preferred over the * operator for matrix multiplication.

In [9]:
A = np.array([[4, 2],
              [3, 5]])

In [10]:
# 1. Compute the transpose and inverse of A.

A_transpose = A.T
A_transpose

array([[4, 3],
       [2, 5]])

In [11]:
# 2. Verify that the product of A and its inverse gives an identity matrix (within rounding error).

A_inverse = np.linalg.inv(A)
output_matrix = np.dot(A, A_inverse)
output_matrix = np.round(output_matrix, 6)
output_matrix

array([[1., 0.],
       [0., 1.]])

3. Explain why np.dot() is preferred over the * operator for matrix multiplication.

- `A * B` performs elementwise multiplication of the corresponding elemenets.
- While `np.dot(A, B)` performs true matrix multiplication according to the mathemtical definition.

## Question 4 — linspace, reshape, and Slicing

1. Create an array of 15 evenly spaced values between 0 and 30 using np.linspace().
2. Reshape it into a 3×5 matrix.
3. Extract the last two rows and the first three columns from the reshaped array.
4. Compute the column-wise mean of this subarray.

In [12]:
# 1. Create an array of 15 evenly spaced values between 0 and 30 using np.linspace()
arr = np.linspace(0, 30, num=15)
arr

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

In [13]:
# 2. Reshape it into a 3×5 matrix.
arr_reshaped = arr.reshape(3, 5)
arr_reshaped

array([[ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857],
       [10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429],
       [21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ]])

In [14]:
# 3. Extract the last two rows and the first three columns from the reshaped array.
extracted_arr = arr_reshaped[-2:, :3]
extracted_arr

array([[10.71428571, 12.85714286, 15.        ],
       [21.42857143, 23.57142857, 25.71428571]])

In [15]:
# 4. Compute the column-wise mean of this subarray.

arr_mean_colwise = np.mean(extracted_arr, axis=0)
arr_mean_colwise

array([16.07142857, 18.21428571, 20.35714286])